FROM node:24-slim

WORKDIR /app

# сначала зависимости
COPY frontend/package*.json ./
RUN npm install

# затем весь фронтенд-код
COPY frontend/ ./

# прокидываем адрес API
ENV VITE_API_URL=http://localhost:8000/api

EXPOSE 5173

# запускаем vite-dev-server
CMD ["sh", "-c", "npm install && npm run dev -- --host 0.0.0.0"]
