version: "3.9"

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn uniplay.asgi:application -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000"
    env_file: .env
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  db:
    image: postgres:16-alpine
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A uniplay worker -l info
    env_file: .env
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

  celerybeat:
    build: .
    command: celery -A uniplay beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file: .env
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  static_volume:
  media_volume:
