# Generated by Django 5.2.1 on 2025-05-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="teams",
            field=models.ManyToManyField(
                blank=True,
                help_text="Команды, зарегистрированные на турнир",
                related_name="tournaments",
                to="tournament.team",
            ),
        ),
    ]
